name: new_CI_image
run-name: Build the Docker image for AIS CI.
env:
  AIS_CI_IMAGE_NAME: ais_ci_${{ inputs.platform }}
  AIS_DOCKER_REGISTRY: ghcr.io/riley-dixon/hipfile-test
  AIS_PR_BASE_URL: https://github.com/ROCm/hipFile/pull
on:
  workflow_call:
    inputs:
      dockerfile_changed:
        # While this seems like a smell to not make this check in this workflow,
        # it allows us to skip the job entirely. This yields the benefit of
        # letting downstream jobs start sooner and keeping the job result as
        # 'skipped' if a new CI image is not needed.
        description: Hint for if this workflow actually needs to run.
        required: true
        type: boolean
      platform:
        required: true
        type: string
    outputs:
      ci_image:
        description: |
          The full name & tag of the CI image to use.
          If a new CI image is produced, returns the new CI image name & tag.
          Otherwise, returns the current CI image name & tag.
        value: >-
          ${{ 
            jobs.build_AIS_image.result == 'skipped' && format('ghcr.io/riley-dixon/hipfile-test/ais_ci_{0}:latest', inputs.platform) ||
            jobs.build_AIS_image.result == 'success' && jobs.build_AIS_image.outputs.new_ci_image ||
            null
          }}
      ci_image_build_satisfied:
        description: |
          Indicates if the CI image is in an acceptable state.
          Set to 'true' if the CI image is unchanged, or if a new CI image was
          built successfully. Otherwise 'false'.
        value: >-
          ${{
            (
              !inputs.dockerfile_changed &&
              jobs.build_AIS_image.result == 'skipped'
            ) ||
            (
              inputs.dockerfile_changed &&
              jobs.build_AIS_image.result == 'success'
            )
          }}
permissions:
  contents: read
  packages: write
jobs:
  build_AIS_image:
    if: ${{ inputs.dockerfile_changed }}
    runs-on: [ubuntu-24.04]
    container: docker:28.5
    outputs:
      new_ci_image: ${{ steps.ci-image.outputs.AIS_CI_IMAGE }}
    steps:
      - name: Set CI environment variables
        run: |
          echo "AIS_CI_IMAGE_TAG=$(echo ${{ github.ref }} | sed 's|[^a-zA-Z0-9]|-|g')" >> "${GITHUB_ENV}"
          echo "AIS_PR_NUMBER=$(echo ${{ github.ref }} | sed 's|[^0-9]||g')" >> "${GITHUB_ENV}"
      - name: Set target AIS CI Image
        id: ci-image
        run: |
          echo "AIS_CI_IMAGE=${AIS_DOCKER_REGISTRY}/${AIS_CI_IMAGE_NAME}:${AIS_CI_IMAGE_TAG}" \
            >> "${GITHUB_OUTPUT}"
          echo "AIS_CI_LATEST_CACHE=${AIS_DOCKER_REGISTRY}/${AIS_CI_IMAGE_NAME}:latest-cache" \
            >> "${GITHUB_OUTPUT}"
      - name: Fetching code repository...
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      - name: Authenticating to GitHub Container Registry.
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Builder
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v3.12.0
        with:
          name: ais-builder
          driver: docker-container
          cache-binary: false # True uses the GHA Cache Backend.
      - name: Build base image for AIS CI
        run: |
          docker buildx build \
            -f "${GITHUB_WORKSPACE}/util/docker/DOCKERFILE.${AIS_CI_IMAGE_NAME}" \
            --label "org.opencontainers.image.description= \
              ${AIS_CI_IMAGE_NAME} Development Image for AIS CI using branch \
              ${{ github.head_ref }} for PR #${AIS_PR_NUMBER}. \
              PR URL: ${AIS_PR_BASE_URL}/${AIS_PR_NUMBER}" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from=type=registry,ref="${{ steps.ci-image.outputs.AIS_CI_IMAGE }}" \
            --cache-from=type=registry,ref="${{ steps.ci-image.outputs.AIS_CI_LATEST_CACHE }}" \
            --push \
            -t "${{ steps.ci-image.outputs.AIS_CI_IMAGE }}" \
            ${GITHUB_WORKSPACE}
